services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - db
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:80
    # networks:
    # - rest-server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    networks:
      - db
    # env_file:
    #   - ./server/.env
networks:
  db:
    driver: bridge
  # rest-server:
  # driver: bridge
