servers:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - db
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:80
  server:
    container_name: server
    build:
      contex: ./server
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    networks:
      - db

networks:
  db:
    driver: bridge
